### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by tekfunk** [sibiraj-s/react-layout-masonry#1]
Just thought I'd note this.  The component is working, but I get this typescript error.

'Masonry' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.ts(2786)

this is with NEXT (app router) 13.5.3 Typescript 5.1.6

**Comment by sibiraj-s** [comment]
Hi, Thanks for reporting this. Should be fixed in v1.0.7
